spring:
  application:
    name: assignment4

  datasource:
    driver-class: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/assignment
    username: postgres
    password: postgres

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp