spring:
  application:
    name: spring-web
  
  datasource:
    driver-class: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/training
    username: postgres
    password: postgres
 
  jpa :  
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp

#sql:
#   init:
#     mode: always